version: "2"
services:

  homeassistant:
    build: ./homeassistant
    ports:
      - "22"
      - "8123"
      - "137"
      - "138"
      - "139"
      - "445"
      - "8123:80"

volumes:
  homeassistant:
