version: "2"
services:

  homeassistant:
    build: ./homeassistant
    expose:
      - "8123"

  nginx:
    build: ./nginx
    depends_on:
      - homeassistant
    ports:
      - "80"

volumes:
  homeassistant:
