version: "2"

volumes:
  homeassistant-data:
  mosquitto-data:

services:

  homeassistant:
    build: ./homeassistant
    ports:
      - "22"
      - "8123"
      - "137"
      - "138"
      - "139"
      - "445"
    volumes:
      - 'homeassistant-data:/data'
    depends_on:
      - mosquitto

  #   environment:
  #     - VIRTUAL_HOST=homeassistant
  #     - VIRTUAL_PORT=8123
  #
  # nginx:
  #   build: ./nginx
  #   depends_on:
  #     - homeassistant
  #   ports:
  #     - "80"
  mosquitto:
    build: ./mosquitto
    environment:
      - VIRTUAL_HOST=mosquitto
      - VIRTUAL_PORT=1883
    ports:
      - "1883"
      - "9001"
    volumes:
      - 'mosquitto-data:/data'
