FROM homeassistant/raspberrypi3-homeassistant:latest

# install utils
RUN apk add --no-cache \
    samba \
    samba-common-tools \
    supervisor

# install root filesystem overlay
COPY /root /

# set a simple samba password for the root user
RUN /bin/echo -e "resin\nresin" | smbpasswd -a -s -c "/etc/samba/smb.conf" root

CMD ["/bin/bash", "/usr/local/bin/start.sh"]