version: "2"

volumes:
  homeassistant-data:
  flicd-data:

services:
  homeassistant:
    build: ./homeassistant
    privileged: true
    ports:
      - "22"
      - "8123"
      - "137"
      - "138"
      - "139"
      - "445"
      - "51827"
    network_mode: host
    volumes:
      - 'homeassistant-data:/data'

  flicd:
    build: ./flicd
    privileged: true
    expose:
      - "5551"
    network_mode: host
    volumes:
      - 'flicd-data:/data'
