version: "2"

volumes:
  homeassistant-data:

services:
  homeassistant:
    build: ./homeassistant
    ports:
      - "22:22"
      - "8123:8213"
      - "137:137"
      - "138:138"
      - "139:139"
      - "445:445"
    volumes:
      - 'homeassistant-data:/data'
