version: "2"

volumes:
  homeassistant-data:
  mosquitto-data:

services:

  homeassistant:
    build: ./homeassistant
    ports:
      - "22"
      - "8123"
      - "137"
      - "138"
      - "139"
      - "445"
    volumes:
      - 'homeassistant-data:/data'
    depends_on:
      - mosquitto

  mosquitto:
    build: ./mosquitto
    environment:
      - VIRTUAL_HOST=mosquitto
      - VIRTUAL_PORT=1883
    ports:
      - "1883"
      - "9001"
    volumes:
      - 'mosquitto-data:/data'
