version: "2"
services:

  homeassistant:
    build: ./homeassistant
    ports:
      - "22"
      - "8123"
      - "137"
      - "138"
      - "139"
      - "445"
  #   environment:
  #     - VIRTUAL_HOST=homeassistant
  #     - VIRTUAL_PORT=8123
  #
  # nginx:
  #   build: ./nginx
  #   depends_on:
  #     - homeassistant
  #   ports:
  #     - "80"
  mosquitto:
    build: ./mosquitto

volumes:
  homeassistant:
