version: "2"

volumes:
  homeassistant:
  mosquitto:

services:

  homeassistant:
    build: ./homeassistant
    ports:
      - "22"
      - "8123"
      - "137"
      - "138"
      - "139"
      - "445"
    volumes:
      - 'homeassistant:/data'
  #   environment:
  #     - VIRTUAL_HOST=homeassistant
  #     - VIRTUAL_PORT=8123
  #
  # nginx:
  #   build: ./nginx
  #   depends_on:
  #     - homeassistant
  #   ports:
  #     - "80"
  mosquitto:
    build: ./mosquitto
    expose:
      - "1883"
      - "9001"
    volumes:
      - 'mosquitto:/data'
